version: 2.1
jobs:
  build-medium:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:
      - run: uname -a
      - run: lscpu

workflows:
  build:
    jobs:
      - build-medium
